// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/cache/weathercache/weathercache.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/cache/weathercache/weathercache.go -destination=mocks/mock_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "weather_service/internal/models"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// GetWeather mocks base method.
func (m *MockCache) GetWeather(ctx context.Context, logger *zap.Logger, city string) (*models.WeatherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeather", ctx, logger, city)
	ret0, _ := ret[0].(*models.WeatherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeather indicates an expected call of GetWeather.
func (mr *MockCacheMockRecorder) GetWeather(ctx, logger, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeather", reflect.TypeOf((*MockCache)(nil).GetWeather), ctx, logger, city)
}

// SetWeather mocks base method.
func (m *MockCache) SetWeather(ctx context.Context, logger *zap.Logger, city string, weathervalue *models.WeatherResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeather", ctx, logger, city, weathervalue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWeather indicates an expected call of SetWeather.
func (mr *MockCacheMockRecorder) SetWeather(ctx, logger, city, weathervalue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeather", reflect.TypeOf((*MockCache)(nil).SetWeather), ctx, logger, city, weathervalue)
}
