// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/weatherservice/weatherservice.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/weatherservice/weatherservice.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "weather_service/internal/models"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetWeather mocks base method.
func (m *MockService) GetWeather(ctx context.Context, logger *zap.Logger, data string) (*models.WeatherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeather", ctx, logger, data)
	ret0, _ := ret[0].(*models.WeatherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeather indicates an expected call of GetWeather.
func (mr *MockServiceMockRecorder) GetWeather(ctx, logger, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeather", reflect.TypeOf((*MockService)(nil).GetWeather), ctx, logger, data)
}
